import { extendTheme, Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import AppLayout from '../common/components/layout/Layout';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <AppLayout>
      <Head>
        <title>Home - Buddly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>Home</Heading>
      </main>
    </AppLayout>
  );
};

export default Home;
